---
- name: Converge
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    dhcp_global_domain_name: austincloud.net
    dhcp_global_domain_name_servers: [1.1.1.3, 1.1.1.1]
    dhcp_global_default_lease_time: 600
    dhcp_global_max_lease_time: 7200
    dhcp_global_authoritative: true
    dhcp_subnets:
      - ip: 192.168.1.0
        netmask: 255.255.255.0
        range:
          - 192.168.1.100
          - 192.168.1.200
        routers: 192.168.1.254

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
